-- DropIndex
DROP INDEX "User_email_key";

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "firstName" DROP DEFAULT,
ALTER COLUMN "lastName" DROP DEFAULT,
ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "password" DROP DEFAULT,
ALTER COLUMN "isFirstLogin" DROP DEFAULT,
ALTER COLUMN "isActivated" DROP DEFAULT,
ALTER COLUMN "isTermsAccepted" DROP DEFAULT,
ALTER COLUMN "accountId" DROP DEFAULT;
